# Module 6.5.2: Create Heatmaps for Weather Parameters

In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

#Let's review how we will use our dependencies. We'll use Pandas to read our CSV file and create the locations and 
#measurements from the DataFrame. We'll use gmaps and the API key to create heatmaps and the locations map, and we'll use 
#the requests dependency to make a request to the Google Places JSON file. This will allow us to get hotel locations from 
#the latitude and longitude of the city.

In [2]:
#Next, we'll read our cities.csv file into a DataFrame
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Fortuna,US,2021-03-25 00:02:13,40.5982,-124.1573,53.01,81,90,10.36
1,1,Khatanga,RU,2021-03-24 23:58:18,71.9667,102.5000,-8.23,96,99,3.47
2,2,Puerto Ayora,EC,2021-03-24 23:57:42,-0.7393,-90.3518,80.01,87,32,1.01
3,3,Tupik,RU,2021-03-25 00:02:14,54.4253,119.9327,17.22,87,38,1.25
4,4,Ushuaia,AR,2021-03-24 23:56:31,-54.8000,-68.3000,42.80,75,20,36.82

In [3]:
#Recall that you use the dtypes method to get the data types of a DataFrame.
#Get the data types.
city_data_df.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

# Module 6.5.2: Create a Maximum Temperature Heatmap

In [4]:
#First, tell gmaps to use your API key. You only need to configure gmaps to use your API key once.
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [5]:
#Next, create the heatmap for the maximum temperature. The general syntax for creating a heatmap is as follows.
# 1. Assign the locations to an array of latitude and longitude pairs.
#locations = [latitude, longitude]
# 2. Assign the weights variable to some values.
#temperatures = # an array of length equal to the locations array length
# 3. Assign the figure variable to the gmaps.figure() attribute.
#fig = gmaps.figure()
# 4. Assign the heatmap_layer variable to the heatmap_layer attribute and add in the locations.
#heatmap_layer = gmaps.heatmap_layer(locations, weights=temperatures)

# 5. Add the heatmap layer.
#fig.add_layer(heatmap_layer)
# 6. Call the figure to plot the data.
#fig

In [6]:
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))

In [7]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=temps, dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

# Module 5.2.5: Create a Percent Humidity Heatmap

In [8]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

# Module 5.2.5: Create a Percent Cloudiness Heatmap

In [9]:
# Heatmap of percent cloudiness
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

# Module 5.2.5: Create a Wind Speed Heatmap

In [10]:
# Heatmap of wind
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

# Module 6.5.3: Get Vacation Criteria

In [11]:
#For the app we are creating, we need to prompt the user to enter the minimum and maximum temperature ranges as 
#floating-point decimal numbers to filter the city_data_df DataFrame

#Recall that you use the input() statement to prompt a user to enter information. To convert the input to a floating-point 
#decimal number, wrap the input() statement with the float() method, like this: float(input()).

#In a new cell, we'll write two input statements for the app that will prompt the customer to add minimum and maximum 
#temperature values and convert these values to floating-point decimals.

# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [12]:
#Recall that you use the loc[] method on the current DataFrame to create a new DataFrame from a current DataFrame. Inside 
#the brackets, add the conditional filter.
#Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.tail()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
226,226,Cairns,AU,2021-03-24 23:58:23,-16.9167,145.7667,86.00,78,86,6.91
229,229,Banjar,ID,2021-03-25 00:03:16,-8.1900,114.9675,80.60,83,20,2.30
231,231,Sao Jose Da Coroa Grande,BR,2021-03-25 00:03:17,-8.8978,-35.1478,78.98,75,46,9.04
233,233,Hervey Bay,AU,2021-03-24 23:58:55,-25.2986,152.8535,80.60,50,0,5.75
234,234,Diffa,NE,2021-03-25 00:03:17,13.3154,12.6113,81.88,16,99,12.06

In [15]:
#Before moving on, determine if the preferred_cities_df DataFrame has any null values for any of the rows.
preferred_cities_df.count()

#Consider the following guidance:
#Depending on the time of year and the seasons, you might have to adjust the minimum and maximum temperature to get enough 
#cities.
#It is a good idea to keep the number of cities to fewer than 200 to make it easier to plot the markers on the heatmap.
#If you have some rows with null values, you'll need to drop them using the dropna() method at the end of your filtering 
#statement when you are creating the new DataFrame.

City_ID       71
City          71
Country       71
Date          71
Lat           71
Lng           71
Max Temp      71
Humidity      71
Cloudiness    71
Wind Speed    71
dtype: int64

In [16]:
preferred_cities_df.dropna()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
2,2,Puerto Ayora,EC,2021-03-24 23:57:42,-0.7393,-90.3518,80.01,87,32,1.01
6,6,Saint-Philippe,RE,2021-03-24 23:54:59,-21.3585,55.7679,77.00,78,0,5.75
13,13,Port Macquarie,AU,2021-03-24 23:56:40,-31.4333,152.9167,80.01,54,0,3.00
15,15,Mahebourg,MU,2021-03-24 23:57:35,-20.4081,57.7000,75.20,94,20,5.75
16,16,Vaini,TO,2021-03-24 23:57:45,-21.2000,-175.2000,75.20,100,90,6.91
...,...,...,...,...,...,...,...,...,...,...
226,226,Cairns,AU,2021-03-24 23:58:23,-16.9167,145.7667,86.00,78,86,6.91
229,229,Banjar,ID,2021-03-25 00:03:16,-8.1900,114.9675,80.60,83,20,2.30
231,231,Sao Jose Da Coroa Grande,BR,2021-03-25 00:03:17,-8.8978,-35.1478,78.98,75,46,9.04
233,233,Hervey Bay,AU,2021-03-24 23:58:55,-25.2986,152.8535,80.60,50,0,5.75
234,234,Diffa,NE,2021-03-25 00:03:17,13.3154,12.6113,81.88,16,99,12.06

# Module 6.5.4 : Map Vacation Criteria

In [17]:
#Using the coordinates from the preferred_cities_df DataFrame, find a hotel using our Google Places API and then retrieve 
#that hotel information. Once we retrieve the hotel information, we'll need to store it so we can reference it and add the 
#information to the pop-up marker.

#Make a copy of the preferred_cities_df DataFrame and name it hotel_df. For the hotel_df, keep the columns "City," 
#"Country," "Max Temp," "Lat," and "Lng." Add a new column to the hotel_df DataFrame to hold the name of the hotel.

# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

              City Country  Max Temp      Lat       Lng Hotel Name
2     Puerto Ayora      EC     80.01  -0.7393  -90.3518
6   Saint-Philippe      RE     77.00 -21.3585   55.7679
13  Port Macquarie      AU     80.01 -31.4333  152.9167
15       Mahebourg      MU     75.20 -20.4081   57.7000
16           Vaini      TO     75.20 -21.2000 -175.2000
17           Kapaa      US     79.00  22.0752 -159.3190
18           Basco      PH     75.24  20.4487  121.9702
21           Jizan      SA     80.60  17.3333   42.6667
23      Port Blair      IN     80.46  11.6667   92.7500
24          Bonthe      SL     78.10   7.5264  -12.5050

# Module 6.5.4: Retrieve Hotels from a Nearby Search

In [18]:
# Dependencies and Setup
import requests
import gmaps

# Import API key
from config import g_key

In [34]:
#To find the nearest establishment to geographic coordinates, use the Google Places Nearby Search request. First, navigate 
#to the Nearby Search requests page.

#For our hotel search, we'll use these parameters:

#1. API key
#2. Latitude and longitude
#3. 5,000-meter radius
#4. Type of place

# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")
        
#Recall that when trying to parse the data from an API request, we need to use a try-except block to handle the error with 
#a statement and continue the retrieval.

hotel_df.head(10)

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

,City,Country,Max Temp,Lat,Lng,Hotel Name
2,Puerto Ayora,EC,80.01,-0.7393,-90.3518,Finch Bay Galapagos Hotel
6,Saint-Philippe,RE,77.00,-21.3585,55.7679,"Chambres d'hôte ""La Trinité"""
13,Port Macquarie,AU,80.01,-31.4333,152.9167,Rydges Port Macquarie
15,Mahebourg,MU,75.20,-20.4081,57.7000,Shandrani Beachcomber Resort & Spa
16,Vaini,TO,75.20,-21.2000,-175.2000,Keleti Beach Resort
17,Kapaa,US,79.00,22.0752,-159.3190,Sheraton Kauai Resort at Coconut Beach
18,Basco,PH,75.24,20.4487,121.9702,Nathaniel's Lodge
21,Jizan,SA,80.60,17.3333,42.6667,شهدان. ابوالحجر
23,Port Blair,IN,80.46,11.6667,92.7500,Welcomhotel Bay Island Port Blair
24,Bonthe,SL,78.10,7.5264,-12.5050,Bonthe Holiday Village

# Module 6.5.4 : Create a Maximum Temperature Heatmap from a Hotel DataFrame

In [35]:
#Before we add pop-up markers with hotel information, let's create a heatmap using the maximum temperature from our 
#hotel_df DataFrame by reusing the code and changing the DataFrame name.

# Add a heatmap of temperature for the vacation spots.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [36]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [40]:
#Now we can add a pop-up marker for each city that displays the hotel name, city name, country, and maximum temperature.

#From the gmaps documentation on how to add markers (Links to an external site.), we need to add an info_box_template that 
#has the following syntax.

info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))